defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/android:api-30
  environment:
    JVM_OPTS: -Xmx3200m

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "android-sdk/build.gradle" }}
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "android-sdk/build.gradle" }}
      - run:
          name: Run tests with coverage
          command: ./gradlew lint test jacocoTestReport
      - store_artifacts:
          path: android-sdk/build/reports
          destination: reports
      - store_test_results:
          path: android-sdk/build/test-results
          destination: test-results
      - run:
          name: Build library
          command: ./gradlew assemble
      - store_artifacts:
          path: android-sdk/build/outputs/aar/
          destination: aar
#      - run:
#          name: Publishing coverage report(codecov.io)
#          when: always
#          command: |
#            curl -s https://codecov.io/bash | bash

  release:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "android-sdk/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "android-sdk/build.gradle" }}
      - run:
          name: Setup Signing Configuration
          command: |
            echo $ORG_GRADLE_PROJECT_SIGNING_KEY | awk 'NR == 1 { print "\nsigning.key=" } 1' ORS='\\n' >> gradle.properties
            echo $ORG_GRADLE_PROJECT_SIGNING_KEY_PWD | awk 'NR == 1 { print "\nsigning.password=" } 1' ORS='' >> gradle.properties
      - run:
          name: Publish to Nexus
          command: ./gradlew publish --stacktrace

workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            # By default a build is only triggered on commits. Lets build for any tag too.
            tags:
              only: /.*/
      - release:
          context: nexus-publish
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
